import type { Metadata } from 'next';
import './globals.css';
//import "bootstrap/dist/css/bootstrap.min.css";
import LenisProvider from './utils/LenisProvider';

export const metadata: Metadata = {
  title: 'Wasabi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <LenisProvider>{children} </LenisProvider>
      </body>
    </html>
  );
}
